import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { FileText, Download, Loader, FileCheck, User, Briefcase } from 'lucide-react';

export default function ContractGenerator() {
  const [formData, setFormData] = useState({
    contractType: 'service',
    party1Name: '',
    party1Email: '',
    party2Name: '',
    party2Email: '',
    serviceDescription: '',
    paymentAmount: '',
    paymentTerms: 'Upon completion',
    startDate: '',
    endDate: '',
    jurisdiction: 'United States'
  });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);

  const generateContract = async () => {
    setLoading(true);

    const contract = `
================================================================================
                           ${formData.contractType.toUpperCase()} AGREEMENT
================================================================================

This Agreement is entered into as of ${formData.startDate || '[Date]'}, by and between:

PARTY 1: ${formData.party1Name || '[Name]'}
Email: ${formData.party1Email || '[Email]'}

AND

PARTY 2: ${formData.party2Name || '[Name]'}
Email: ${formData.party2Email || '[Email]'}

--------------------------------------------------------------------------------
                              1. SERVICES
--------------------------------------------------------------------------------

${formData.party1Name} agrees to provide the following services to ${formData.party2Name}:

${formData.serviceDescription || '[Description of services]'}

--------------------------------------------------------------------------------
                            2. COMPENSATION
--------------------------------------------------------------------------------

In consideration for the Services, ${formData.party2Name} agrees to pay ${formData.party1Name}
the sum of $${formData.paymentAmount || '[Amount]'}.

Payment Terms: ${formData.paymentTerms}

--------------------------------------------------------------------------------
                              3. TERM
--------------------------------------------------------------------------------

This Agreement shall commence on ${formData.startDate || '[Start Date]'} and continue
until ${formData.endDate || '[End Date]'}, unless terminated earlier.

--------------------------------------------------------------------------------
                           4. TERMINATION
--------------------------------------------------------------------------------

Either party may terminate this Agreement with 30 days written notice.

--------------------------------------------------------------------------------
                          5. CONFIDENTIALITY
--------------------------------------------------------------------------------

Both parties agree to keep confidential all proprietary information.

--------------------------------------------------------------------------------
                           6. GOVERNING LAW
--------------------------------------------------------------------------------

This Agreement shall be governed by the laws of ${formData.jurisdiction}.

================================================================================
                              SIGNATURES
================================================================================

Party 1: _________________________    Date: _____________

Party 2: _________________________    Date: _____________

================================================================================
        Generated by DocuMaster - documaster.app
================================================================================
`;

    setTimeout(() => {
      setResult(contract);
      setLoading(false);
    }, 1000);
  };

  const downloadContract = () => {
    if (!result) return;
    const blob = new Blob([result], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `contract_${formData.contractType}_${Date.now()}.txt`;
    a.click();
  };

  return (
    <div className="py-8">
      <Helmet>
        <title>Contract Generator - Create Legal Documents | DocuMaster</title>
        <meta name="description" content="Generate professional contracts and agreements automatically. Create service agreements, NDAs, and more for free." />
      </Helmet>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-gradient-to-br from-indigo-500 to-blue-500 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <FileCheck className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-secondary-900 mb-2">Contract Generator</h1>
          <p className="text-secondary-600">Generate professional contracts automatically</p>
        </div>

        <div className="card mb-6">
          <h3 className="font-semibold text-secondary-900 mb-4">Contract Type</h3>
          <div className="grid grid-cols-3 gap-3">
            {[
              { value: 'service', label: 'Service Agreement' },
              { value: 'nda', label: 'Non-Disclosure' },
              { value: 'employment', label: 'Employment' }
            ].map((type) => (
              <button
                key={type.value}
                onClick={() => setFormData({ ...formData, contractType: type.value })}
                className={`p-3 rounded-lg border-2 text-center transition-colors ${
                  formData.contractType === type.value
                    ? 'border-primary-500 bg-primary-50'
                    : 'border-secondary-200 hover:border-secondary-300'
                }`}
              >
                {type.label}
              </button>
            ))}
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-6">
          <div className="card">
            <h3 className="font-semibold text-secondary-900 mb-4 flex items-center gap-2">
              <User className="w-5 h-5 text-primary-600" /> First Party (Provider)
            </h3>
            <div className="space-y-3">
              <input
                type="text"
                placeholder="Full Name"
                value={formData.party1Name}
                onChange={(e) => setFormData({ ...formData, party1Name: e.target.value })}
                className="input"
              />
              <input
                type="email"
                placeholder="Email Address"
                value={formData.party1Email}
                onChange={(e) => setFormData({ ...formData, party1Email: e.target.value })}
                className="input"
              />
            </div>
          </div>

          <div className="card">
            <h3 className="font-semibold text-secondary-900 mb-4 flex items-center gap-2">
              <Briefcase className="w-5 h-5 text-primary-600" /> Second Party (Client)
            </h3>
            <div className="space-y-3">
              <input
                type="text"
                placeholder="Full Name / Company"
                value={formData.party2Name}
                onChange={(e) => setFormData({ ...formData, party2Name: e.target.value })}
                className="input"
              />
              <input
                type="email"
                placeholder="Email Address"
                value={formData.party2Email}
                onChange={(e) => setFormData({ ...formData, party2Email: e.target.value })}
                className="input"
              />
            </div>
          </div>
        </div>

        <div className="card mb-6">
          <h3 className="font-semibold text-secondary-900 mb-4">Contract Details</h3>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-secondary-700 mb-1">Service Description</label>
              <textarea
                placeholder="Describe the services to be provided..."
                value={formData.serviceDescription}
                onChange={(e) => setFormData({ ...formData, serviceDescription: e.target.value })}
                className="input min-h-[80px]"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">Payment Amount ($)</label>
                <input
                  type="number"
                  placeholder="0.00"
                  value={formData.paymentAmount}
                  onChange={(e) => setFormData({ ...formData, paymentAmount: e.target.value })}
                  className="input"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">Payment Terms</label>
                <select
                  value={formData.paymentTerms}
                  onChange={(e) => setFormData({ ...formData, paymentTerms: e.target.value })}
                  className="input"
                >
                  <option>Upon completion</option>
                  <option>Net 30 days</option>
                  <option>Monthly</option>
                  <option>Milestone-based</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">Start Date</label>
                <input
                  type="date"
                  value={formData.startDate}
                  onChange={(e) => setFormData({ ...formData, startDate: e.target.value })}
                  className="input"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">End Date</label>
                <input
                  type="date"
                  value={formData.endDate}
                  onChange={(e) => setFormData({ ...formData, endDate: e.target.value })}
                  className="input"
                />
              </div>
            </div>
          </div>
        </div>

        <button onClick={generateContract} disabled={loading} className="btn btn-primary w-full mb-6">
          {loading ? <Loader className="w-5 h-5 animate-spin mr-2" /> : <><FileText className="w-4 h-4 mr-2" />Generate Contract</>}
        </button>

        {result && (
          <div className="card bg-secondary-900 text-white font-mono text-sm overflow-x-auto">
            <pre className="whitespace-pre-wrap p-4">{result}</pre>
            <button onClick={downloadContract} className="btn bg-white text-secondary-900 hover:bg-secondary-100 w-full mt-4">
              <Download className="w-4 h-4 mr-2" /> Download Contract
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
