import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { ChartBar as BarChart3, Download, Loader, ChartBar as FileBarChart, ChartPie as PieChart, TrendingUp } from 'lucide-react';

export default function ReportGenerator() {
  const [formData, setFormData] = useState({
    reportTitle: '',
    reportType: 'business',
    period: 'monthly',
    summary: '',
    keyFindings: '',
    recommendations: ''
  });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);

  const generateReport = async () => {
    setLoading(true);

    const report = `
================================================================================
                         ${formData.reportTitle.toUpperCase() || 'ANALYSIS REPORT'}
================================================================================

Report Type: ${formData.reportType.charAt(0).toUpperCase() + formData.reportType.slice(1)} Report
Period: ${formData.period.charAt(0).toUpperCase() + formData.period.slice(1)}
Generated: ${new Date().toLocaleDateString()}

================================================================================
                           EXECUTIVE SUMMARY
================================================================================

${formData.summary || 'This report provides a comprehensive analysis of the specified period, highlighting key metrics, trends, and actionable recommendations.'}

================================================================================
                           KEY FINDINGS
================================================================================

${formData.keyFindings || `
1. Overall performance has shown consistent improvement over the reporting period.

2. Key metrics indicate positive growth in core business areas.

3. Opportunity areas have been identified for further optimization.

4. Market conditions remain favorable for strategic expansion.
`}

================================================================================
                           RECOMMENDATIONS
================================================================================

${formData.recommendations || `
1. Continue investment in high-performing areas.

2. Address identified gaps through targeted initiatives.

3. Monitor key metrics on a weekly basis.

4. Review strategies quarterly for optimal results.
`}

================================================================================
                            METRICS SUMMARY
================================================================================

| Metric              | Current    | Previous   | Change    |
|---------------------|------------|------------|-----------|
| Revenue             | $XXX,XXX   | $XXX,XXX   | +X.X%     |
| Growth Rate         | X.X%       | X.X%       | +X.X%     |
| Customer Count      | XXXX       | XXXX       | +XX       |
| Satisfaction Score  | X.X/5.0    | X.X/5.0    | +X.X      |

================================================================================
                          CONCLUSION
================================================================================

This report demonstrates continued progress toward established goals. The data
supports a positive outlook with specific areas requiring attention for
optimal outcomes.

================================================================================
        Generated by DocuMaster - Professional Report Templates
================================================================================
`;

    setTimeout(() => {
      setResult(report);
      setLoading(false);
    }, 1000);
  };

  const downloadReport = () => {
    if (!result) return;
    const blob = new Blob([result], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${formData.reportTitle.replace(/\s+/g, '_') || 'report'}_${Date.now()}.txt`;
    a.click();
  };

  return (
    <div className="py-8">
      <Helmet>
        <title>Report Generator - Auto-Generate Professional Reports | DocuMaster</title>
        <meta name="description" content="Generate professional business reports automatically. Create executive summaries, performance reports, and analysis documents." />
      </Helmet>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-gradient-to-br from-emerald-500 to-teal-500 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <FileBarChart className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-secondary-900 mb-2">Report Generator</h1>
          <p className="text-secondary-600">Auto-generate professional business reports</p>
        </div>

        <div className="card mb-6">
          <h3 className="font-semibold text-secondary-900 mb-4">Report Type</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { value: 'business', label: 'Business', icon: BarChart3 },
              { value: 'financial', label: 'Financial', icon: TrendingUp },
              { value: 'performance', label: 'Performance', icon: PieChart },
              { value: 'analysis', label: 'Analysis', icon: FileBarChart }
            ].map((type) => (
              <button
                key={type.value}
                onClick={() => setFormData({ ...formData, reportType: type.value })}
                className={`p-4 rounded-lg border-2 text-center transition-colors ${
                  formData.reportType === type.value
                    ? 'border-primary-500 bg-primary-50'
                    : 'border-secondary-200 hover:border-secondary-300'
                }`}
              >
                <type.icon className="w-5 h-5 mx-auto mb-2 text-primary-600" />
                <span className="text-sm">{type.label}</span>
              </button>
            ))}
          </div>
        </div>

        <div className="card mb-6">
          <h3 className="font-semibold text-secondary-900 mb-4">Report Details</h3>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">Report Title</label>
                <input
                  type="text"
                  placeholder="e.g., Q4 Financial Report"
                  value={formData.reportTitle}
                  onChange={(e) => setFormData({ ...formData, reportTitle: e.target.value })}
                  className="input"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-secondary-700 mb-1">Period</label>
                <select
                  value={formData.period}
                  onChange={(e) => setFormData({ ...formData, period: e.target.value })}
                  className="input"
                >
                  <option value="daily">Daily</option>
                  <option value="weekly">Weekly</option>
                  <option value="monthly">Monthly</option>
                  <option value="quarterly">Quarterly</option>
                  <option value="yearly">Yearly</option>
                </select>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-secondary-700 mb-1">Executive Summary</label>
              <textarea
                placeholder="Brief overview of the report..."
                value={formData.summary}
                onChange={(e) => setFormData({ ...formData, summary: e.target.value })}
                className="input min-h-[80px]"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-secondary-700 mb-1">Key Findings</label>
              <textarea
                placeholder="Main findings and observations..."
                value={formData.keyFindings}
                onChange={(e) => setFormData({ ...formData, keyFindings: e.target.value })}
                className="input min-h-[80px]"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-secondary-700 mb-1">Recommendations</label>
              <textarea
                placeholder="Suggested actions..."
                value={formData.recommendations}
                onChange={(e) => setFormData({ ...formData, recommendations: e.target.value })}
                className="input min-h-[80px]"
              />
            </div>
          </div>
        </div>

        <button onClick={generateReport} disabled={loading} className="btn btn-primary w-full mb-6">
          {loading ? <Loader className="w-5 h-5 animate-spin mr-2" /> : <><FileBarChart className="w-4 h-4 mr-2" />Generate Report</>}
        </button>

        {result && (
          <div className="card bg-secondary-900 text-white font-mono text-sm overflow-x-auto">
            <pre className="whitespace-pre-wrap p-4">{result}</pre>
            <button onClick={downloadReport} className="btn bg-white text-secondary-900 hover:bg-secondary-100 w-full mt-4">
              <Download className="w-4 h-4 mr-2" /> Download Report
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
